### ISSUE TITLE
enhance run command to support diagonals

### ISSUE THREAD

**Issue by rmsr** [sneezymud/sneezymud#11]
right now it only supports single-character direction commands. add support for a space-separated direction list, so you can use diagonals.

extra features:
 - abort the command when an error occurs.
 - implement as a task or something so the mud doesn't lag out for long direction lists
 - use the same pathfinding as 'goto': "run to [destination]"

originally reported:

https://bitbucket.org/cizra/sneezymud/issues/18/run-command-should-append-move-commands-to

**Comment by cizra** [comment]
How do you disambiguate ne=n;e from ne=northeast? We can have "if at least one space is present, all must be" or somesuch.

**Comment by rmsr** [comment]
Tthe presence of spaces in the directions list should be sufficient for detection. How many existing users are there of the run command though? We could just switch over to spaces-required completely.

Updated the ticket with some more ideas.

I'm also curious what similar commands on other MUDs are like.

**Comment by drewhershey** [comment]
Another mud I've played had a similar command that used alternate, single characters to represent diagonals - something like k, l, m, n for nw, ne, se, sw. Not very intuitive, but maybe an easier change to make code-wise. I would definitely use the run command a lot more if it supported diagonals.

**Comment by cizra** [comment]
The 2 MUDs I know of that support 'run' command don't do diagonals.

**Comment by cizra** [comment]
Done. Enjoy.
