### ISSUE TITLE
men of the night

### ISSUE THREAD

**Issue by rmsr** [sneezymud/sneezymud#133]
Add some male ones so there's gender balance.

Also fix the ladies so they recognize the gender of their customers.

**Comment by cizra** [comment]
We already have bouncers, we need pimps next!

**Comment by Aion2501** [comment]
Aye, girl characters need that hot girl on girl action. 

Or at the very least not to get a male script if they do interact with those evening ladies. Kinda awkward.

**Comment by rmsr** [comment]
I think one should watch a lot of gigolo-related videos to do research for this. Preferably as a female or at least with one present.
