### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by drewhershey** [sneezymud/sneezymud#162]
Is there still a Discord running where I could potentially get some advice if needed re: things like setting up a test environment/copy of the code on my system?

I've been programming for a long time but pretty much all in easier, less powerful languages and in a Windows environment. I feel like a huge beginner when I look into setting a copy of Sneezy up on my own, although I've only attempted it in Windows 10 which is probably dumb when there's already a guide for doing it in Linux.

**Comment by rmsr** [comment]
Drew please email me at my github profile address, I'll hook you up.

**Comment by rmsr** [comment]
Yo hershey-san, that's [rmsr@lab.net](mailto:rmsr@lab.net) 😸  I'd email you but you have no contact information in your github profile.
