### ISSUE TITLE
Docker builds in main repo

### ISSUE THREAD

**Issue by rmsr** [sneezymud/sneezymud#2]
Similar to the travis-ci setup in #1, merge the Docker files into the main repo, and link the repo to the sneezymud team on docker hub (https://hub.docker.com/u/sneezymud/). @cizra, I need your docker hub username so I can add you as an owner to the team (user 'cizra' not found - still available!)

**Comment by rmsr** [comment]
Looks like docker cloud also has a CI mode, wonder if it integrates with github in the same fashion as travis-ci.

**Comment by wershlak** [comment]
obsolete now
