### ISSUE TITLE
Crash bug with throw

### ISSUE THREAD

**Issue by parkscs** [sneezymud/sneezymud#236]
I came across a bug today by accident and it crashes the mud when sent (I've duplicated this to test).  I've sent the details to Aion and I can forward it on to whoever wants to work on this.

**Comment by cizra** [comment]
Uhh, can we have details here please?

**Comment by parkscs** [comment]
H:690 M:159 P:100.0 V:123 > throw empty south finneyssssssssssssssssssssssss
sssssssddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddd

Pretty sure the strength length on the target is the issue.

**Comment by cizra** [comment]
Thanks @parkscs, I fixed it.
