### ISSUE TITLE
"A small red stick" crashing mud

### ISSUE THREAD

**Issue by mftrnr** [sneezymud/sneezymud#54]
Twice the mud crash when attempting to drop "A small red stick" from my inventory, single item drop just clearing out my inventory mud instantly crashed. 

Both times I was standing in Market Square in GH, as soon as command was entered mud insta crashed, after first crash logged back in item was still there and on second attempt to drop the item in the same room it crashed again.

**Comment by Hordeking** [comment]
Stack Trace:

0. 0x00007f6ca4040f90 in __dynamic_cast ()   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
**1. 0x00007f6ca5b752c1 in TTrap::armGrenade (this=this@entry=0xb254b70,  ch=ch@entry=0xc134fe0) at code/obj/obj_trap.cc:400**
2. 0x00007f6ca6a89bc9 in TTrap::dropMe (this=0xb254b70, ch=0xc134fe0,  showroom=SHOW_ROOM) at code/misc/inventory.cc:271
3. 0x00007f6ca6a887b9 in TBeing::doDrop (this=this@entry=0xc134fe0,  argument=..., tng=tng@entry=0x0, forcedDrop=forcedDrop@entry=false) at code/misc/inventory.cc:444
4. 0x00007f6ca6b9a990 in TBeing::doCommand (this=this@entry=0xc134fe0, cmd=cmd@entry=CMD_DROP, argument=..., vict=vict@entry=0x0, typedIn=typedIn@entry=true) at code/misc/parse.cc:773
5. 0x00007f6ca6ba0202 in TBeing::parseCommand (this=0xc134fe0, orig_arg=..., typedIn=typedIn@entry=true, doAlias=doAlias@entry=true) at code/misc/parse.cc:2041
6. 0x00007f6ca714f553 in processAllInput () at code/sys/connect.cc:2896
7. 0x00007f6ca71bed37 in TMainSocket::handleTimeAndSockets (this=<optimized out>) at code/sys/socket.cc:496
8. 0x00007f6ca71bee67 in procHandleTimeAndSockets::run (this=<optimized out>, pl=...) at code/sys/socket.cc:1668
9. 0x00007f6ca71b740f in TScheduler::run (this=this@entry=0x7ffc11af7c20, pulseNum=pulseNum@entry=311929) at code/sys/process.cc:229
10. 0x00007f6ca71c1dca in TMainSocket::gameLoop (this=0x11cb500) at code/sys/socket.cc:1845
11. 0x00007f6ca7110e89 in run_the_game () at code/sys/comm.cc:125
12. 0x00000000004063b9 in main (argc=3, argv=0x7ffc11af8008) at code/main.cc:71

**Comment by Sinner-Aion** [comment]
The crash only seems to occur under certain circumstances. Dropping multiple sticks in the lab or various other rooms has no effect. However, the monument of fallen heroes in Market Square, the old fisherman, and certain other objects/mobiles present in combination will trigger the crash. 

Load object red-stick 
Duplicate at will.

**Comment by cizra** [comment]
Fix @ https://github.com/sneezymud/sneezymud/pull/56
