### ISSUE TITLE
Skill Change: Portal

### ISSUE THREAD

**Issue by Aion2501** [sneezymud/sneezymud#60]
This skill (amongst others) has been changed many times over the years. I believe its current state is not in the best interests of the game.

I propose removing the counter from portal. 

There is a short lifespan once first entered, but there is also a max number counter for times a player or number of players can pass through it before the portal disappears. Currently seems to be at 8. Lets remove that limit. No more leaving partial groups behind, discouraging group behavior, etc.

**Comment by grotberg** [comment]
I think removing the user limit is reasonable.  What is the current lifespan?

My thoughts on portal is that is SHOULD be a relatively epic, completely awesome ability that is really cool when it gets used, but maybe shouldn't be handed out like candy.  To that end I'd propose the following other changes as well (some of these are easy to implement, others less so):
1) Increase the piety cost for portal substantially.  I'd put it around 90%.  Altering the fabric of reality is not something undertaken by the gods lightly.
2) Possibly require a special focus or expensive (expendable) component.  Again, just thinking in the vein that using portal should be epic, not something used all the time.
3) Require the caster to "attune" to the portal locations before they can portal there.  This one probably requires a bit of code to make work, but could also mean we could add other portal-able waypoints that players can gain access to with exploration.

**Comment by Aion2501** [comment]
Gabe, I like #3. 

Maybe add a statue at each waypoint that the cleric has to pray at before they can portal to the location.

The days of portaling to mobs or objects are gone. Portals don't last half an hour anymore... it's currently down to 5 minutes I think. And not everyone fits through. Not very epic right now. 

I've also always thought mages should have a version of this ability, as in D&D, WoW, etc.

**Comment by nenbeely** [comment]
I like #1 and #3 combined from Gabe's list, and I'd agree on removing the player counter.

**Comment by Aion2501** [comment]
It was set to 10 charges and 5 minute lifespan. I've edited this to 20 charges and 10 minute lifespan. Will test and see if further changes or rollbacks become necessary.
