### ISSUE TITLE
Mounts: Deikhans I Have Your Back

### ISSUE THREAD

**Issue by Aion2501** [sneezymud/sneezymud#62]
Deikhans have long been a forgotten class, thieves being right behind them (pun intended). Their primary complaint being issues with mounts. Some changes that may help:

- When mounted, the player and mount need to count as a single mobile towards the max limit of the room, to prevent mounts from being left behind or being cumbersome.

- New mounts need to be introduced to the game to handle various environments, such as **going underwater** or having a high enough HP pool to deal with particularly vicious AoE’s (or preferably go D&D style and have the mount ignore AoE).
Adding a dozen cool, new mounts to the game would be great regardless. I'll help design some. :)

- Looting from a mount is currently restricted, which does make sense, but in practicality causes problems for deikhans. Perhaps allowing them to loot while mounted, but generating a message to the room, creating the illusion that they dismount first to loot the corpse and return to their mount.

**Comment by grotberg** [comment]
Looting from a mount could be rolled into the "ride" skills. (Skill check to loot, otherwise fall flat on face.  Difficulty increases with object weight.)

Damage reduction to mount could be rolled into the existing advanced riding skill.  We could also make this cover things like: getting your mount into smaller spaces and all those other quality of life issues for deikhans.  Just need to make a comprehensive list.  Here's a start:
* Room limits
* Room heights
* ??

**Comment by nenbeely** [comment]
I haven't looked into the specific combat benefits Deikhans receive from mounts, but another angle is to leave some of these inconveniences (as long as they aren't major balance issues that render the class useless in a large portion of fights), but further increase the benefits of mounted combat.

I could also see doing a little bit of diversity - two separate specialized skills around mounted combat, one for a tanky deikhan build and one for an offensive-minded build.

**Comment by Leyline77** [comment]
Yeah Deikhans, which would seem more "tanky" than a warrior, are no where
near the tank a warrior is, and a LOT of the time we cannot bring amount
into the area for combat, making their special flavor just like a warrior
-15 levels. (or worse)

(Clerics are also often better tanks than deikhans)

Thanks for considering this class for some work :)

**Comment by wershlak** [comment]
So this is mostly resolved in the deikhan update. I'm going to close this out and If someone disagrees they can reopen :)
