### ISSUE TITLE
Looting treasue chest in Massive Cavern next to Masstrizial had negative talens

### ISSUE THREAD

**Issue by GenrouTheGhost** [sneezymud/sneezymud#67]
This appears to be an error in the "treasure" proc, a weird proc that also somehow shows a "treasure" item as the contents of the relevant container (instead of xxx talens). Maybe randomize it from a flat 5 million too.

```You start getting items from a large stone chest.
You get a treasure from a large stone chest.
There were -2147483648 talens.
Sorry, you can't do that!
You can get nothing more from a large stone chest!
```

**Comment by GenrouTheGhost** [comment]
Yeah, I couldn't purchase anything after that, couldn't rent, etc. Aion had
to just restore what money I had prior to picking it up to fix.

**Comment by rmsr** [comment]
I believe this is a bug in the "treasure" object proc
