### ISSUE TITLE
Chests remain unlocked and open after reboot

### ISSUE THREAD

**Issue by GenrouTheGhost** [sneezymud/sneezymud#68]
Example of one is

 A frozen solid chest is pushed against the wall. (opened) in troll caves where daytime Cladosporium is at. There are many others that do it as well, I think some actually do lock again, but majority of them are staying open past reboots.

The branch we had with Imm had the same issue but if I recall correctly he had found the fix for it on that one.

**Comment by rmsr** [comment]
Fixed in #166, woo!
