### ISSUE TITLE
Bug: Armor Spell Crit

### ISSUE THREAD

**Issue by Aion2501** [sneezymud/sneezymud#70]
I crit an armor spell on Heishiro and compared it to the normal armor spell on myself. 

**Thor**
Spell : 'armor'
     Modifies Armor/AC by -100 points
     Expires in   3333 updates, Bits set: NOBITS

**Heishiro**
Spell : 'armor'
     Modifies Armor/AC by -24 points
     Expires in   6708 updates, Bits set: NOBITS

For some reason the crit armor gave 1/4th the armor. Maybe this was a code typo where someone meant to add -240 points instead of -24? Other spells usually double on a crit. I know Bless does. Should at least be -200.

**Comment by rmsr** [comment]
armor cast on someone else is vastly less effective than one cast on yourself. Heishiro's armor is 100 divided by eight (someone else) = 12, times two (crit) = 24.
