### ISSUE TITLE
2-Hand Weapons

### ISSUE THREAD

**Issue by Aion2501** [sneezymud/sneezymud#76]
There are a lot of junk weapons in the game and a few really fantastic ones. But currently there is no real incentive to use 2-Handed Weapons over 1-Handed Weapons. Generally, you'd expect 2-H to do more damage and sometimes that is the case, but everyone knows what you REALLY want is a great 1-H that does similar damage. Maybe use an offhand with a proc or a shield in tandem.

To address that, I suggest modifying weapons that have the [Paired] flag to deal extra damage. Perhaps a 1.5x damage modifier or doubling the damage bonus from the strength stat. IE: +25% cap > +50% cap.  Maybe some additional hitroll that could be dex based in a similar way.  

This would give players real options and decisions to make regarding using a 1-H and shield, two 1-H, or a 2-H. Balancing offense/defense.

**Comment by TheRealHeishiro** [comment]
Increasing the damage on 2h fantastic!  The hitroll per round is quite lack lusting compare to 1h. Adding 1-2 more hit into the formula would help.

**Comment by drewhershey** [comment]
2H/paired weapons already do get a flat 10% damage bonus over 1H but as you said it's not nearly enough to incentivize them over dual wielding even mediocre 1H weapons, assuming the character has the dual wield skill even to something like "lousy".

Weapon Damage Formula:
1) Base Damage = Damage Level * 1.75
2) If the weapon is 2H, Base Damage = Base Damage * 1.1
3) Flux = Base Damage * Damage Deviation / 10
4) Actual Damage Range = Base Damage +/- Flux

Examples with actual items: 

- Dwarven Maul: 
    - Drops from Archbishop Thrombul in Dwarven Temple, level 51 mob
    - Damage level - 51, Damage deviation - 8
    - Base Damage = 51 * 1.75 => 89.25
    - Weapon is 2H, so Base Damage = 89.25 * 1.1 => 98.175
        - 98.175 / 1.75 = 56.1 (So true damage level is 56)
    - Flux = 98.175 * 8 / 10 => 78.54
    - Damage Range = 98.175 - 78.54 to 98.175 + 78.54 => 19 - 176 (always rounded down)

- The Hand of Justice: 
    - Drops from Judge Albert Finney in Xanesla, level 89 mob
    - Damage level - 56, Damage deviation - 0
    - Base Damage = 56 * 1.75 = 98.0
    - 1H weapon, so no 10% boost to base damage
    - No damage deviation, so final damage range is 98 - 98

So with the way it works now, a very strong but relatively easy-to-obtain 2H weapon like a dwarven maul does the exact same average damage as a 1H weapon that drops off a much, much higher level/more difficult mob in a much higher level, more dangerous zone. That's the only real advantage I can see that 2H weapons have over 1H - easier to obtain for similar amount of damage.

However, that's only true if you don't dual wield. With maxed dual wielding your offhand damage is only reduced by 30%. A character with 205 speed, haste, celerite, and maxed weapon specialization for their mainhand weapon will get 3 to 4 attacks with their mainhand (or a 2H weapon) and 2 to 3 attacks at 70% damage with their offhand, per round. Doing some quick maths that ignores things like strength bonuses and assumes all attacks land:

Dwarven Maul (damage level 51, but gets 10% 2H bonus):
    - Max avg. dmg / round: 98 dmg * 4 attacks = 392
Dual-wielded damage level 51 weapons:
    - Max avg. dmg / round: (89 dmg * 4 main hand attacks) + (89 dmg * 3 offhand attacks * 70% damage) = 356 + 186 = 542

(542 - 392) / 392 = 38% more average damage per round from dual wielding two weapons of the same base damage level as a given 2H. Not to mention all the extra chances to crit from the 2 - 3 more attacks per round.

With no training in dual wield your offhand will still get the same number of attacks but will only do 10% of your potential max damage, meaning about 2.5% less total damage/round than a comparable 2H. So as soon as you get dual wielding to even a fairly low level a 2H weapon starts losing ground quickly.

I'm not really sure what the best way to address this issue would be. Assuming what I've written here is accurate (I think it is, but am fully ready to be proven wrong) to even get 2H weapons _equal_ with a skilled dual wielder you'd need to increase the 2H's damage output by a lot either by adding more attacks or increasing damage done per attack. The other concern is making sure not to turn dual wielding into something no one ever wants to use over a 2H.

**Comment by wershlak** [comment]
Closing this
