### ISSUE TITLE
Vindicator quest: Ryoken guard portion is broken

### ISSUE THREAD

**Issue by rmsr** [sneezymud/sneezymud#89]
A person wrote on Facebook, "Check to see if all the quests are working. [xxx] would like to his vindy quest, soon, and as far as I know, the Ryoken guard portion is broke."

**Comment by wershlak** [comment]
Not broken. There's a bunch of us that have completed this quest. 

It can be a bit frustrating that the normal guards will swarm on you as you work your way towards the one you need to kill but that's a balance issue not a defect.
